import { GameAttributes } from '../seeds/game-seeds.ts';

module.exports = {
  up: async (queryInterface, Sequelize) => {
    await queryInterface.bulkInsert('games', [
      {
        slug: 'the-witcher-3-wild-hunt',
        name: 'The Witcher 3: Wild Hunt',
        released: new Date('2015-05-19'),
        tba: false,
        background_image: 'https://example.com/witcher3.jpg',
        rating: 4.9,
        rating_top: 5,
        metacritic: 93,
        playtime: 100,
        suggestions_count: 15,
        updated: new Date(),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        slug: 'red-dead-redemption-2',
        name: 'Red Dead Redemption 2',
        released: new Date('2018-10-26'),
        tba: false,
        background_image: 'https://example.com/rdr2.jpg',
        rating: 4.8,
        rating_top: 5,
        metacritic: 97,
        playtime: 80,
        suggestions_count: 20,
        updated: new Date(),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        slug: 'the-legend-of-zelda-breath-of-the-wild',
        name: 'The Legend of Zelda: Breath of the Wild',
        released: new Date('2017-03-03'),
        tba: false,
        background_image: 'https://example.com/zelda.jpg',
        rating: 4.9,
        rating_top: 5,
        metacritic: 97,
        playtime: 60,
        suggestions_count: 12,
        updated: new Date(),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        slug: 'cyberpunk-2077',
        name: 'Cyberpunk 2077',
        released: new Date('2020-12-10'),
        tba: false,
        background_image: 'https://example.com/cyberpunk.jpg',
        rating: 4.2,
        rating_top: 5,
        metacritic: 86,
        playtime: 40,
        suggestions_count: 30,
        updated: new Date(),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        slug: 'grand-theft-auto-v',
        name: 'Grand Theft Auto V',
        released: new Date('2013-09-17'),
        tba: false,
        background_image: 'https://example.com/gta5.jpg',
        rating: 4.7,
        rating_top: 5,
        metacritic: 96,
        playtime: 50,
        suggestions_count: 18,
        updated: new Date(),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        slug: 'god-of-war',
        name: 'God of War',
        released: new Date('2018-04-20'),
        tba: false,
        background_image: 'https://example.com/godofwar.jpg',
        rating: 4.9,
        rating_top: 5,
        metacritic: 94,
        playtime: 40,
        suggestions_count: 22,
        updated: new Date(),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        slug: 'hades',
        name: 'Hades',
        released: new Date('2020-09-17'),
        tba: false,
        background_image: 'https://example.com/hades.jpg',
        rating: 4.7,
        rating_top: 5,
        metacritic: 93,
        playtime: 35,
        suggestions_count: 25,
        updated: new Date(),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        slug: 'dark-souls-iii',
        name: 'Dark Souls III',
        released: new Date('2016-04-12'),
        tba: false,
        background_image: 'https://example.com/darksouls3.jpg',
        rating: 4.6,
        rating_top: 5,
        metacritic: 89,
        playtime: 45,
        suggestions_count: 13,
        updated: new Date(),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        slug: 'animal-crossing-new-horizons',
        name: 'Animal Crossing: New Horizons',
        released: new Date('2020-03-20'),
        tba: false,
        background_image: 'https://example.com/animalcrossing.jpg',
        rating: 4.5,
        rating_top: 5,
        metacritic: 90,
        playtime: 50,
        suggestions_count: 10,
        updated: new Date(),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        slug: 'doom-eternal',
        name: 'Doom Eternal',
        released: new Date('2020-03-20'),
        tba: false,
        background_image: 'https://example.com/doom.jpg',
        rating: 4.8,
        rating_top: 5,
        metacritic: 88,
        playtime: 20,
        suggestions_count: 15,
        updated: new Date(),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ]);
  },

  down: async (queryInterface, Sequelize) => {
    await queryInterface.bulkDelete('games', null, {});
  },
};